/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pavelnemec' at '1/24/18 9:41 AM' with Gradle 3.2
 *
 * @author pavelnemec, @date 1/24/18 9:41 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
